import type { Heuristic } from "@/lib/quality/types";

const asNumber = (v: unknown, fallback: number): number =>
  typeof v === "number" && Number.isFinite(v) ? v : fallback;

// Range-based emoji detection avoids carrying a giant table. Includes the
// common emoji blocks plus emoji presentation selector (FE0F).
const EMOJI_RE =
  /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{1F000}-\u{1F2FF}\u{1F900}-\u{1F9FF}\u{1F600}-\u{1F64F}]/gu;

const VAGUE_TITLE_RE = /^(update|fix|wip|patch|changes?|misc|stuff|chore)$/i;

const AI_WATERMARK_RE =
  /\b(as an ai|i (?:am|'m) an ai|i cannot directly|i'?ve updated the code|here(?:'s| is) the updated|certainly[!.,]|of course[!.,]|let me (?:know if|help)|language model|i hope this helps|sure[!.,] (?:here|i)|generated by (?:chatgpt|copilot|claude|gemini))\b/i;

const ISSUE_REF_RE = /(?:#\d+|(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#\d+)/i;

export const prTextHeuristics: Heuristic[] = [
  {
    id: "pr.body_empty",
    group: "pr",
    label: "Empty PR body",
    description: "Body is missing or whitespace-only.",
    weight: 2,
    defaultEnabled: true,
    run(ctx) {
      const body = (ctx.pr.body ?? "").trim();
      return { failed: body.length === 0, value: body.length };
    },
  },
  {
    id: "pr.body_too_long",
    group: "pr",
    label: "Wall-of-text PR body",
    description: "Body exceeds the configured character limit.",
    weight: 1,
    defaultEnabled: true,
    defaultThreshold: 2500,
    thresholdKind: "number",
    run(ctx, threshold) {
      const max = asNumber(threshold, 2500);
      const len = (ctx.pr.body ?? "").length;
      return {
        failed: len > max,
        value: len,
        reason: len > max ? `${len} chars (>${max})` : undefined,
      };
    },
  },
  {
    id: "pr.body_emoji_count",
    group: "pr",
    label: "Excessive emojis in body",
    description: "Many AI-generated PRs are decorated with emojis.",
    weight: 1,
    defaultEnabled: true,
    defaultThreshold: 2,
    thresholdKind: "number",
    run(ctx, threshold) {
      const max = asNumber(threshold, 2);
      const matches = (ctx.pr.body ?? "").match(EMOJI_RE) ?? [];
      return {
        failed: matches.length > max,
        value: matches.length,
        reason:
          matches.length > max ? `${matches.length} emojis (>${max})` : undefined,
      };
    },
  },
  {
    id: "pr.body_inline_code_refs",
    group: "pr",
    label: "Excessive inline code references",
    description: "Walls of inline ` ` references often indicate AI summaries.",
    weight: 1,
    defaultEnabled: true,
    defaultThreshold: 5,
    thresholdKind: "number",
    run(ctx, threshold) {
      const max = asNumber(threshold, 5);
      const body = ctx.pr.body ?? "";
      // Count single-backtick spans only (skip ``` fenced blocks).
      const stripped = body.replace(/```[\s\S]*?```/g, "");
      const inline = stripped.match(/`[^`\n]+`/g) ?? [];
      return {
        failed: inline.length > max,
        value: inline.length,
        reason:
          inline.length > max ? `${inline.length} inline refs (>${max})` : undefined,
      };
    },
  },
  {
    id: "pr.title_vague",
    group: "pr",
    label: "Vague PR title",
    description:
      "Title is one of: update / fix / wip / patch / changes / misc / stuff / chore, or under 8 chars, or emoji-only.",
    weight: 2,
    defaultEnabled: true,
    run(ctx) {
      const title = (ctx.pr.title ?? "").trim();
      const stripped = title.replace(EMOJI_RE, "").trim();
      const isEmojiOnly = title.length > 0 && stripped.length === 0;
      const failed =
        title.length === 0 ||
        title.length < 8 ||
        VAGUE_TITLE_RE.test(title) ||
        isEmojiOnly;
      return { failed, value: title };
    },
  },
  {
    id: "pr.no_linked_issue",
    group: "pr",
    label: "No linked issue",
    description: "Body has no #N reference or fixes/closes/resolves keyword.",
    weight: 1,
    defaultEnabled: false,
    run(ctx) {
      const body = ctx.pr.body ?? "";
      return { failed: !ISSUE_REF_RE.test(body) };
    },
  },
  {
    id: "pr.honeypot_hit",
    group: "pr",
    label: "Honeypot keyword hit",
    description:
      "PR body contains hidden honeypot text from the project's PR template — typically copy-pasted by AI bots.",
    weight: 3,
    defaultEnabled: true,
    run(ctx) {
      const body = (ctx.pr.body ?? "").toLowerCase();
      const honeypots = ctx.project.prTemplateHoneypots
        .map((s) => s.trim().toLowerCase())
        .filter(Boolean);
      const hit = honeypots.find((h) => body.includes(h));
      return { failed: Boolean(hit), value: hit ?? null };
    },
  },
  {
    id: "pr.ai_watermark",
    group: "pr",
    label: "AI watermark phrase",
    description:
      'Body contains a phrase commonly emitted by language models (e.g. "as an AI", "Here is the updated").',
    weight: 3,
    defaultEnabled: true,
    run(ctx) {
      const body = ctx.pr.body ?? "";
      const m = body.match(AI_WATERMARK_RE);
      return {
        failed: Boolean(m),
        value: m?.[0] ?? null,
        reason: m ? `Matched: "${m[0]}"` : undefined,
      };
    },
  },
];
