import type { Heuristic } from "@/lib/quality/types";

const asNumber = (v: unknown, fallback: number): number =>
  typeof v === "number" && Number.isFinite(v) ? v : fallback;

// Range-based emoji detection avoids carrying a giant table. Includes the
// common emoji blocks plus emoji presentation selector (FE0F).
export const EMOJI_RE =
  /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{1F000}-\u{1F2FF}\u{1F900}-\u{1F9FF}\u{1F600}-\u{1F64F}]/gu;

export const VAGUE_TITLE_RE =
  /^(update|fix|wip|patch|changes?|misc|stuff|chore)$/i;

// GitHub's web-UI default titles when the user clicks the pencil-edit icon
// and doesn't change the title (e.g. "Update README.md", "Create foo.ts").
export const GITHUB_DEFAULT_TITLE_RE =
  /^(update|create|delete|rename|add)\s+\S+$/i;

export function isTitleVague(title: string): boolean {
  const trimmed = (title ?? "").trim();
  const stripped = trimmed.replace(EMOJI_RE, "").trim();
  const isEmojiOnly = trimmed.length > 0 && stripped.length === 0;
  return (
    trimmed.length === 0 ||
    trimmed.length < 8 ||
    VAGUE_TITLE_RE.test(trimmed) ||
    GITHUB_DEFAULT_TITLE_RE.test(trimmed) ||
    isEmojiOnly
  );
}

const AI_WATERMARK_RE =
  /\b(as an ai|i (?:am|'m) an ai|i cannot directly|i'?ve updated the code|here(?:'s| is) the updated|certainly[!.,]|of course[!.,]|let me (?:know if|help)|language model|i hope this helps|sure[!.,] (?:here|i)|generated (?:with|by) claude code|generated by pr agent|generated by github copilot|generated by (?:chatgpt|copilot|claude|gemini))\b/i;

const ISSUE_REF_RE = /(?:#\d+|(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#\d+)/i;

const HTML_COMMENT_RE = /<!--[\s\S]*?-->/g;

/**
 * Extract distinctive lines from a PR template that, if echoed in the body,
 * indicate the contributor filled in the template instead of writing freeform.
 * We pick up markdown headings (`# ...`, `## ...`) and checklist items
 * (`- [ ]`, `* [x]`) — both are common in real templates and unlikely to
 * appear by coincidence in a fresh body. HTML comments (the typical "delete
 * this" instruction blocks) are stripped first.
 */
export function extractTemplateMarkers(template: string): string[] {
  const cleaned = template.replace(HTML_COMMENT_RE, "");
  const out = new Set<string>();
  for (const rawLine of cleaned.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line) continue;
    if (/^#{1,6}\s+\S/.test(line)) {
      out.add(line.replace(/^#{1,6}\s+/, "").toLowerCase());
      continue;
    }
    const checkbox = /^[-*]\s+\[[ xX]\]\s+(.+)$/.exec(line);
    if (checkbox) {
      const text = checkbox[1].trim();
      if (text.length >= 4) out.add(text.toLowerCase());
    }
  }
  return Array.from(out);
}

export const prTextHeuristics: Heuristic[] = [
  {
    id: "pr.body_empty",
    group: "pr",
    label: "Empty PR body",
    description: "Body is missing or whitespace-only.",
    weight: 2,
    defaultEnabled: true,
    run(ctx) {
      const body = (ctx.pr.body ?? "").trim();
      return { failed: body.length === 0, value: body.length };
    },
  },
  {
    id: "pr.body_too_long",
    group: "pr",
    label: "Wall-of-text PR body",
    description: "Body exceeds the configured character limit.",
    weight: 1,
    defaultEnabled: true,
    defaultThreshold: 2500,
    thresholdKind: "number",
    run(ctx, threshold) {
      const max = asNumber(threshold, 2500);
      const len = (ctx.pr.body ?? "").length;
      return {
        failed: len > max,
        value: len,
        reason: len > max ? `${len} chars (>${max})` : undefined,
      };
    },
  },
  {
    id: "pr.body_emoji_count",
    group: "pr",
    label: "Excessive emojis in body",
    description: "Many AI-generated PRs are decorated with emojis.",
    weight: 1,
    defaultEnabled: true,
    defaultThreshold: 2,
    thresholdKind: "number",
    run(ctx, threshold) {
      const max = asNumber(threshold, 2);
      const matches = (ctx.pr.body ?? "").match(EMOJI_RE) ?? [];
      return {
        failed: matches.length > max,
        value: matches.length,
        reason:
          matches.length > max ? `${matches.length} emojis (>${max})` : undefined,
      };
    },
  },
  {
    id: "pr.body_inline_code_refs",
    group: "pr",
    label: "Excessive inline code references",
    description: "Walls of inline ` ` references often indicate AI summaries.",
    weight: 1,
    defaultEnabled: true,
    defaultThreshold: 5,
    thresholdKind: "number",
    run(ctx, threshold) {
      const max = asNumber(threshold, 5);
      const body = ctx.pr.body ?? "";
      // Count single-backtick spans only (skip ``` fenced blocks).
      const stripped = body.replace(/```[\s\S]*?```/g, "");
      const inline = stripped.match(/`[^`\n]+`/g) ?? [];
      const failed = inline.length > max;
      return {
        failed,
        value: inline.length,
        reason: failed ? `${inline.length} inline refs (>${max})` : undefined,
        penaltyPoints: failed ? inline.length - max : 0,
      };
    },
  },
  {
    id: "pr.title_vague",
    group: "pr",
    label: "Vague PR title",
    description:
      'Title is a single vague word (update / fix / wip / patch / changes / misc / stuff / chore), GitHub\'s web-UI default ("Update README.md"), under 8 chars, or emoji-only.',
    weight: 2,
    defaultEnabled: true,
    run(ctx) {
      const title = (ctx.pr.title ?? "").trim();
      return { failed: isTitleVague(title), value: title };
    },
  },
  {
    id: "pr.no_linked_issue",
    group: "pr",
    label: "No linked issue",
    description: "Body has no #N reference or fixes/closes/resolves keyword.",
    weight: 1,
    defaultEnabled: false,
    run(ctx) {
      const body = ctx.pr.body ?? "";
      return { failed: !ISSUE_REF_RE.test(body) };
    },
  },
  {
    id: "pr.honeypot_hit",
    group: "pr",
    label: "Honeypot keyword hit",
    description:
      "PR body contains hidden honeypot text from the project's PR template — typically copy-pasted by AI bots.",
    weight: 4,
    defaultEnabled: true,
    run(ctx) {
      const body = (ctx.pr.body ?? "").toLowerCase();
      const honeypots = ctx.project.prTemplateHoneypots
        .map((s) => s.trim().toLowerCase())
        .filter(Boolean);
      const hit = honeypots.find((h) => body.includes(h));
      return { failed: Boolean(hit), value: hit ?? null };
    },
  },
  {
    id: "pr.uses_template",
    group: "pr",
    label: "PR doesn't use the repo's PR template",
    description:
      "Repo ships a PR template (e.g. .github/PULL_REQUEST_TEMPLATE.md) but the body shows no sign of using it — no template headings or checklist items appear. Skipped when the repo has no template.",
    weight: 4,
    defaultEnabled: true,
    run(ctx) {
      const template = (ctx.prTemplate ?? "").trim();
      if (template.length === 0) return { failed: false, reason: "No template in repo" };
      const markers = extractTemplateMarkers(template);
      if (markers.length === 0) {
        return { failed: false, reason: "Template has no distinctive markers" };
      }
      const body = (ctx.pr.body ?? "").toLowerCase();
      if (body.length === 0) {
        return {
          failed: true,
          value: `0/${markers.length}`,
          reason: "Empty body — template not used",
        };
      }
      const matched = markers.filter((m) => body.includes(m));
      return {
        failed: matched.length === 0,
        value: `${matched.length}/${markers.length} markers`,
        reason:
          matched.length === 0 ? "No template headings or checklist items in body" : undefined,
      };
    },
  },
  {
    id: "pr.ai_watermark",
    group: "pr",
    label: "AI watermark phrase",
    description:
      'Body contains a phrase commonly emitted by language models (e.g. "as an AI", "Here is the updated").',
    weight: 4,
    defaultEnabled: true,
    run(ctx) {
      const body = ctx.pr.body ?? "";
      const m = body.match(AI_WATERMARK_RE);
      return {
        failed: Boolean(m),
        value: m?.[0] ?? null,
        reason: m ? `Matched: "${m[0]}"` : undefined,
      };
    },
  },
];
